sudo: false
language: python
install:
  - pip install -U pip tox coveralls
script:
  - tox
  - coveralls
matrix:
matrix:
  allow_failures:
    - env: TOXENV=py35-djmaster-lpclient4
    - env: TOXENV=py35-djmaster-lpclient5

    - env: TOXENV=py36-djmaster-lpclient4
    - env: TOXENV=py36-djmaster-lpclient5

  include:
    - python: 2.7
      env: TOXENV=py27-dj18-lpclient4
    - python: 2.7
      env: TOXENV=py27-dj18-lpclient5

    - python: 3.4
      env: TOXENV=py34-dj19-lpclient5

    - python: 3.5
      env: TOXENV=py35-dj110-lpclient4
    - python: 3.5
      env: TOXENV=py35-dj111-lpclient5
    - python: 3.5
      env: TOXENV=py35-dj20-lpclient5
    - python: 3.5
      env: TOXENV=py35-djmaster-lpclient5

    - python: 3.6
      env: TOXENV=py36-dj20-lpclient5
    - python: 3.6
      env: TOXENV=py36-djmaster-lpclient5
