language: python
python:
  - 2.7
  - 3.3
  - 3.4
install:
  - pip install coverage coveralls
  - pip install -r requirements-test.txt
script:
  - coverage run --source=djlaterpay setup.py test
after_success:
  coveralls
