language: python
sudo: false
install:
  - pip install tox==2.1.1
env:
  - TOX_ENV=python27-django14-lpclient32
  - TOX_ENV=python27-django14-lpclient40
  - TOX_ENV=python27-django16-lpclient32
  - TOX_ENV=python27-django16-lpclient40
  - TOX_ENV=python27-django17-lpclient32
  - TOX_ENV=python27-django17-lpclient40
  - TOX_ENV=python27-django18-lpclient32
  - TOX_ENV=python27-django18-lpclient40
  - TOX_ENV=python27-djangodev-lpclient32
  - TOX_ENV=python27-djangodev-lpclient40
  - TOX_ENV=python33-django16-lpclient32
  - TOX_ENV=python33-django16-lpclient40
  - TOX_ENV=python33-django17-lpclient32
  - TOX_ENV=python33-django17-lpclient40
  - TOX_ENV=python33-django18-lpclient32
  - TOX_ENV=python33-django18-lpclient40
  - TOX_ENV=python33-djangodev-lpclient32
  - TOX_ENV=python33-djangodev-lpclient40
  - TOX_ENV=python34-django16-lpclient32
  - TOX_ENV=python34-django16-lpclient40
  - TOX_ENV=python34-django17-lpclient32
  - TOX_ENV=python34-django17-lpclient40
  - TOX_ENV=python34-django18-lpclient32
  - TOX_ENV=python34-django18-lpclient40
  - TOX_ENV=python34-djangodev-lpclient32
  - TOX_ENV=python34-djangodev-lpclient40
  - TOX_ENV=cov
  - TOX_ENV=flake8
script:
  - tox -e $TOX_ENV
matrix:
  fast_finish: true
  allow_failures:
    - env: TOX_ENV=python27-djangodev-lpclient32
    - env: TOX_ENV=python27-djangodev-lpclient40
    - env: TOX_ENV=python33-djangodev-lpclient32
    - env: TOX_ENV=python33-djangodev-lpclient40
    - env: TOX_ENV=python34-djangodev-lpclient32
    - env: TOX_ENV=python34-djangodev-lpclient40
